spring:
  datasource:
    username: sa
    password:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
#    hikari:
#      jdbc-url: jdbc:h2:~/test
#    initialization-mode: always
  h2:
    console:
      enabled: true
